---
kind: Deployment

spec:
  
  replicas: 1
  template:
    spec:
      containers:
      - name: spring-restful-webservice
        image: vikramdonekal/spring-restful-webservice
        ports:
        - containerPort: 9200
    metadata:
      labels:
        app: spring-restfull-webservice
  selector:
    matchLabels:
      app: spring-restfull-webservice
apiVersion: apps/v1
metadata:	
  labels:
    app: spring-restfull-webservice
  name: spring-restfull-webservice
