---
kind: Deployment

spec:

  replicas: 1
  template:
    spec:
      containers:
      - name: spring-graphql
        image: vikramdonekal/spring-graphql
        ports:
        - containerPort: 9206
    metadata:
      labels:
        app: spring-graphql
  selector:
    matchLabels:
      app: spring-graphql
apiVersion: apps/v1
metadata:
  labels:
    app: spring-graphql
  name: spring-graphql

