# Base Alpine Linux based image with OpenJDK JRE only
FROM openjdk:8-jre-alpine


# copy application WAR (with libraries inside)
COPY jar/Restful_webservice-0.0.1-SNAPSHOT.jar /Restful_webservice-0.0.1-SNAPSHOT.jar


#Expose Port to access from outside container
EXPOSE 9200


# specify default command
CMD ["/usr/bin/java", "-jar", "-Dspring.profiles.active=test", "/Restful_webservice-0.0.1-SNAPSHOT.jar"]
