# Base Alpine Linux based image with OpenJDK JRE only
FROM openjdk:8-jre-alpine


# copy application WAR (with libraries inside)
COPY jar/Graphql-0.0.1-SNAPSHOT.jar /Graphql-0.0.1-SNAPSHOT.jar


#Expose Port to access from outside container
EXPOSE 9206


# specify default command
CMD ["/usr/bin/java", "-jar", "-Dspring.profiles.active=test", "/Graphql-0.0.1-SNAPSHOT.jar"]

